{
 "title": "Log Queries",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "400 related errors",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({filename=\"/var/log/nginx/access.log\"} |~ \"HTTP/1.1\\\" [4][0-9][0-9]\" [1m])",
     "legendFormat": "400 related error"
    }
   ]
  },
  {
   "title": "rate of http codes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\r\n  {filename=\"/var/log/nginx/access.log\"}\r\n  | regexp `\\\"[^\\\"]+\\\"\\s(?P<status>\\d{3})\\s`\r\n  [1m] )"
    }
   ]
  },
  {
   "title": "Max TAT / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "max_over_time(\r\n{filename=\"/var/log/nginx/access.log\"} |= \"TAT=\"\r\n| regexp `TAT=\\\"(?P<tat>[0-9]+(?:\\.[0-9]+)?)\\\"`\r\n| unwrap tat [30s]\r\n) ",
     "legendFormat": "max TAT"
    }
   ]
  },
  {
   "title": "Successful Response rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({filename=\"/app/ubaapi/logs/UBAAPI.log\"} |= \"FT RESPONSE_CODE TO SAVE ==> 00\" [1m])",
     "legendFormat": "Success count"
    }
   ]
  }
 ]
}